# Generated by Django 2.2.4 on 2019-12-21 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('reduced_url', models.CharField(max_length=250)),
                ('auteur', models.CharField(max_length=250)),
                ('compteur', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout de l'url")),
            ],
            options={
                'verbose_name': 'miniurl',
                'ordering': ['date'],
            },
        ),
    ]
