# Generated by Django 2.2.4 on 2019-12-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniurl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniurl',
            name='url',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
